version: "3"
services:
  web:
    env_file:
      - ${APP_ENV:-local}.env
    networks:
      - webnet
    depends_on:
      - mongo
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 80:80
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - webnet
networks:
  webnet:
